name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint & Prettier
      run: |
        npm run prettier
        npm run lint
  
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build 
      run: npm run build 
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-artifact
        path: build

  deploy-surge:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'alexnguyenn'
    needs: [lint]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: build-artifact
    
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploy preview to Surge
      run: npx surge ./build alexnguyenn-test-app-preview.surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    
