name: ci

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint & Prettier
      run: |
        npm run prettier
        npm run lint
  
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build 
      run: npm run build 
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-artifact
        path: build

  deploy-surge:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'alexnguyenn' && github.event_name == 'pull_request'
    needs: [lint, build]
    env:
      SURGE_DOMAIN: ${{ format('https://{0}-{1}-preview-pr{2}.surge.sh', github.repository_owner, 
        github.event.repository.name, github.event.pull_request.number) }}
    
    steps:
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: build-artifact
    
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploy preview to Surge
      run: surge ./ ${{ env.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      
    - uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview is deployed to 

    - name: Share deployment link
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Preview is deployed to ${{ env.SURGE_DOMAIN }}
        edit-mode: replace
